enum {
    TIMELINE_TAG_USER_REG,
    TIMELINE_TAG_USER_LEVELUP,
    TIMELINE_TAG_USER_AIRDROP,
    TIMELINE_TAG_USER_BUY_HOUSE,
    TIMELINE_TAG_USER_BUY_CAR,
    TIMELINE_TAG_USER_BUY_FUEL,
    TIMELINE_TAG_USER_BUY_STORE,
    TIMELINE_TAG_USER_BUY_AMMU,
    TIMELINE_TAG_USER_BUY_GARAGE,
    TIMELINE_TAG_SERVER_STARTED,
}