#define ATTACH_INDEX_HANDCUFF	0
#define ATTACH_INDEX_GELDSACK	1
#define ATTACH_INDEX_JOB		2
#define ATTACH_INDEX_HELM		3
#define ATTACH_INDEX_PIZZA		4
#define ATTACH_INDEX_BRILLE		5
#define ATTACH_INDEX_CAP		6
#define ATTACH_INDEX_BANDANA	7