enum FahrzeugData {
	fDatabaseID,
	fErstellt,
	fModelID,
	Float:fPosition[4],
	fColor[2],
	fPaintjob,
	fKennzeichen[10],
	fAbgeschleppt,
	fParkkralle,
	fKilometer,
	Float:fTank,
	fRang,
	fTuning[14],
	fFraktion,
	fGruppe,
	fAutohaus,
	fNebenjob,
	fNebenjobDuty,
	fGarage,
	fGPark,
	fFahrschule,
	fSupmobil,
	Text3D:fSupmobil3DText,
	fZiviroller,
	fImportCar,
	fKurrierCar,
	fPreis,
	Text3D:fLabel,
	fSupMobilObj[4],
	fBesitzer[MAX_PLAYER_NAME],
	fBesitzerID,
	fPizzaObjekt,
	fkGeld,
	fkWaffe[2],
	fkDrogen,
	fkUpgradeRespawn,
	fJobEXP,
	fJobFahrer,
	fPDObject,
	fSirene[5],
	bool:fSireneBool,
	fBankrob,
	bool:fNeonStatus,
	fNeonColor,
	fNeonObj[2],
	fLastDriver[MAX_PLAYER_NAME],
	fAttachedObject[2],
	fTruckMats,
	fTuningGemeldet
}
new FahrzeugInfo[MAX_VEHICLES][FahrzeugData];

#define MAX_VEHICLE_PLAYER_LIST			(10)

new PrivateCarList[MAX_PLAYERS][MAX_VEHICLE_PLAYER_LIST];