//Models News Definitionen
new SkinordnungGovernment = mS_INVALID_LISTID;
new SkinordnungSAPD = mS_INVALID_LISTID;
new SkinordnungSFPD = mS_INVALID_LISTID;
new SkinordnungMEDIC = mS_INVALID_LISTID;
new SkinordnungFIRE = mS_INVALID_LISTID;
new SkinordnungFBI = mS_INVALID_LISTID;
new SkinordnungOrdnungsamt = mS_INVALID_LISTID;
new SkinordnungSanNews = mS_INVALID_LISTID;
new SkinordnungGrove = mS_INVALID_LISTID;
new SkinordnungBallas = mS_INVALID_LISTID;
new SkinordnungVagos = mS_INVALID_LISTID;
new SkinordnungAztecas = mS_INVALID_LISTID;
new SkinordnungRifa = mS_INVALID_LISTID;
new SkinordnungTriads = mS_INVALID_LISTID;
new SkinordnungDaNangBoys = mS_INVALID_LISTID;
new SkinordnungBikers = mS_INVALID_LISTID;
new SkinordnungItalia = mS_INVALID_LISTID;
new SkinordnungRussia = mS_INVALID_LISTID;

new SkinsBoy = mS_INVALID_LISTID;
new SkinsGirl = mS_INVALID_LISTID;

new DrogenTimer[MAX_PLAYERS];

//Admins
new gPlayerLogged[MAX_PLAYERS];

//News - RosaLife Reloaded
new bool:CopHasBeenContracted = false;
new bool:BlockedZugDuty;
new hooked_trainspawn[MAX_VEHICLES];
new Text3D:AdmDutyLabel[MAX_PLAYERS];
new PDInnenHacking;
new WaitToFindTimer[MAX_PLAYERS];
new FischTimer[MAX_PLAYERS];
new SatOrtung = 0;
new SwatDutyName[MAX_PLAYERS][MAX_PLAYER_NAME];
new AllPaycheckstring[MAX_PLAYERS][500];
new DashcamTimer[MAX_PLAYERS];
new PaintBallCount[MAX_PLAYERS];
new PaintBallSpree[MAX_PLAYERS];
new AnrufenTimer[MAX_PLAYERS];
new bool:PoliceAufbrechenUsed = false;
new bool:engine, bool:lights, bool:alarm, bool:doors, bool:bonnet, bool:boot = false, bool:objective;
new bool:Motor[MAX_VEHICLES], bool:Licht[MAX_VEHICLES], bool:DOOR[MAX_VEHICLES], bool:Motorhaube[MAX_VEHICLES], bool:Kofferraum[MAX_VEHICLES], bool:Neon[MAX_VEHICLES];
new bool:lspdaufzu, bool:lspd2aufzu, bool:lspd3aufzu;
new CarRadio[MAX_VEHICLES];
new CarRadioUrl[MAX_VEHICLES][128];
new bool:Radio[MAX_VEHICLES];
new Year, Month, Day;
new Hour, Minute, Second;
new ServerRestartFolgt = 0;
new bool:Importfahrzeug = false;
new bool:Kurrierfahrzeug[3];
new SaveAllTimer;
new Handschellen[MAX_PLAYERS];
new KnastTimer[MAX_PLAYERS];
new PrisonTimer[MAX_PLAYERS];
new PDEquiptTimer[MAX_PLAYERS];
new CountdownTimer;
new CountdownVar;
new CountdownString[32];
new MutePlayerTimer[MAX_PLAYERS];
new PrisonPlayerTimer[MAX_PLAYERS];
new WerbungSperrePlayerTimer[MAX_PLAYERS];
new autohauscarmodelid[MAX_PLAYERS][MAX_VEHICLES];
new autohauscarid[MAX_PLAYERS][MAX_VEHICLES];
new Float:KMHPos[MAX_PLAYERS][3];
new TachoTimer[MAX_PLAYERS];
new OldKilometer[MAX_VEHICLES];
new NewKilometer[MAX_VEHICLES];
new ProbefahrtCar[MAX_PLAYERS];
new ProbefahrtTime[MAX_PLAYERS];
new ProbefahrtTimer[MAX_PLAYERS];
new ImportCarTime, ImportCarTimer, ImportCar;
new KurrierCarTime[3], KurrierCarTimer[3], KurrierCar[3];
new Float:markerX[MAX_PLAYERS], Float:markerY[MAX_PLAYERS], Float:markerZ[MAX_PLAYERS], Float:markerA[MAX_PLAYERS], markerInt[MAX_PLAYERS], markerVw[MAX_PLAYERS];
new SpielerLKWTrailer[MAX_PLAYERS];
new FahrschulCar[MAX_VEHICLES];
new schulung[MAX_PLAYERS];
new stopACFehlerpunkte[MAX_PLAYERS];
new Fehlerpunkte[MAX_PLAYERS];
new FahrenTimer[MAX_PLAYERS];
new HealthTimer[MAX_PLAYERS];
new Weather[3];
new SanNewsDuty;
new FeuerwehrDuty;
new MedicDuty;
new CopDuty;
new FBIDuty;
new OAmtDuty;
new Bankrob;
new PlayerBankRobTimer[MAX_PLAYERS];
new PlayerBankRobSec[MAX_PLAYERS];
new BankRobGeldSack[10];
new BankRobGeldSackSpawned[2];
new Text3D:BankRobGeldSackLabel[10];
new BankRobGeld[10];
new BankRobVan = INVALID_VEHICLE_ID;
new BankRobAmLaufen;
new BankRobGeldGesamt;
new BankAttacker;
new Float:FahrzeugTank[MAX_VEHICLES];
new PizzaSpieler[MAX_PLAYERS][5];
new Float:PizzaKundenPos[MAX_PLAYERS][3];
new Float:MuellHausPos[MAX_PLAYERS][3];
new Float:PizzaKofferraumPos[MAX_PLAYERS][3];
new Float:MuellAutoPos[MAX_PLAYERS][3];
new PizzaAusgeliefert[MAX_PLAYERS];
new PizzaReinlegenTimer[MAX_PLAYERS];
new PizzaRausnehmenTimer[MAX_PLAYERS];
new PizzaBekommenTimer[MAX_PLAYERS];
new Float:WaltonKofferraumPos[MAX_PLAYERS][3];
new PayDayTimer[MAX_PLAYERS];
new CamFahrten[MAX_PLAYERS];
new LoadingTimer[MAX_PLAYERS];
new MuellmannTimer[MAX_PLAYERS];
new MuellObjekt[MAX_PLAYERS][29];
new LandwirtObjekt[MAX_PLAYERS][72];
new LandwirtTimer[MAX_PLAYERS];
new NotrufSperre[MAX_PLAYERS][5];
new NotrufTimer[MAX_PLAYERS][5];
new FallschirmPickup;
new RobBarTimer[MAX_PLAYERS];
new Float:RobBarValue[MAX_PLAYERS];
new RobBarAllowed[MAX_PLAYERS];
new ServerLadenStatus;
new ServerLadenTimer;
new ServerSpeichernStatus;
new ServerSpeichernTimer;
new SDMTimer[MAX_PLAYERS];
new Text3D:BlitzerLabel[MAX_BLITZER];
new ServerNewsVar = 0;
new PilotenTimer[MAX_PLAYERS];
new BusfahrerTimer[MAX_PLAYERS];
new BombenTimer[MAX_PLAYERS];
new PaintballSpieler[5];
new TazerTimer[MAX_PLAYERS];
new Float:Tot_X[MAX_PLAYERS];
new Float:Tot_Y[MAX_PLAYERS];
new Float:Tot_Z[MAX_PLAYERS];
new Tot_Int[MAX_PLAYERS];
new Tot_World[MAX_PLAYERS];
new FallPlayerTimer[MAX_PLAYERS];
new DeadTimer[MAX_PLAYERS];
new KrankenhausTimer[MAX_PLAYERS];
new name43[MAX_PLAYER_NAME][50];
new name44[MAX_PLAYER_NAME][50];
new FreikaufModelID[MAX_PLAYERS][14];
new FreikaufDatabaseID[MAX_PLAYERS][14];
new FreikaufKey[MAX_PLAYERS];
new PlayerFireTimer[MAX_PLAYERS][3];
new GeldkofferTimer[MAX_PLAYERS];
new WerkzeugTimer[MAX_PLAYERS];
new FillATMTimer[MAX_PLAYERS];
new RepVorgangTimer[MAX_PLAYERS];
new ATMKaputt[MAX_PLAYERS][14];
new BlitzerKaputt[MAX_PLAYERS][14];
new DiceTimer[MAX_PLAYERS];
new oamtbasemapschranke;
new WaffenTransporter = INVALID_VEHICLE_ID;
new WaffenTransportTimer = 0;
new WaffenTransporterMats = 0;
new WaffenTransporterFrakID = 0;

new Float:AfkX[MAX_PLAYERS],Float:AfkY[MAX_PLAYERS],Float:AfkZ[MAX_PLAYERS];
new Afk[MAX_PLAYERS];
new lastUpdate[MAX_PLAYERS];
new Text3D:Afklabel[MAX_PLAYERS];
new Afkversuche[MAX_PLAYERS];
new Afktimer[MAX_PLAYERS];
new afktimedrestka[MAX_PLAYERS];
new LoseHealthTimer[MAX_PLAYERS];

//Tore & Schranken - RosaLife Reloaded

new LSPDGarage, LSPDGarageZ = 0;
new LSPDSchranke, LSPDSchrankeZ = 0;
new FBITor, FBITorZ = 0;
new RussenTor, RussenTorZ = 0;
new MautSchranke[7];
new bool:MautStatus[7];
new lspddoor, lspddoor2, lspddoor3, lspddoorWK;
new NewsTor[2];
new NewsStudioTor;
new BombenTor;
new BombenTorHealth = 10000;
//new MedicFahrstuhl;

//new sannews;
new LottoJackpot = 0;
new bool:LottoFind = false;
new LottoWandJackpot[2];

//Pickups - RosaLife Reloaded
new ImportCarPickup;
new KurrierPickup[3];

//Menü´s - RosaLife Reloaded
new Menu:Schwarzmarkt;
new Menu:BSNMenu;

//PlayerTextdraws - RosaLife Reloaded
new PlayerText:SpectateTD[MAX_PLAYERS];
new PlayerText:TutorialTD[MAX_PLAYERS][6];
new PlayerText:PlusMinusTD[MAX_PLAYERS];
new PlayerText:ICPBox[MAX_PLAYERS];
new PlayerText:ICPTitel[MAX_PLAYERS];
new PlayerText:ICPMessage[MAX_PLAYERS];
new PlayerText:ICPMessageEdit[MAX_PLAYERS];
new PlayerText:ICPHitsound[MAX_PLAYERS];
new PlayerText:ICPHitsoundEdit[MAX_PLAYERS];
new PlayerText:ICPCamera[MAX_PLAYERS];
new PlayerText:ICPCameraEdit[MAX_PLAYERS];
new PlayerText:ICPHandy[MAX_PLAYERS];
new PlayerText:ICPHandyEdit[MAX_PLAYERS];
new PlayerText:ICPBlinker[MAX_PLAYERS];
new PlayerText:ICPBlinkerEdit[MAX_PLAYERS];
new PlayerText:ICPSave[MAX_PLAYERS];
new PlayerText:ICPOChat[MAX_PLAYERS];
new PlayerText:ICPOChatEdit[MAX_PLAYERS];
new PlayerText:Freeze[MAX_PLAYERS];
new PlayerText:EXPInfo[MAX_PLAYERS];
new PlayerText:LevelUP[MAX_PLAYERS];
new PlayerText:Tacho[MAX_PLAYERS][13];
new PlayerText:Gangfight[MAX_PLAYERS][8];
new PlayerText:WantedDraw[MAX_PLAYERS];
new PlayerText:TankenDraw[MAX_PLAYERS][7];
new PlayerText:BankraubTD[MAX_PLAYERS][6];
new PlayerText:RobBar[MAX_PLAYERS][3];
new PlayerText:StatsDraw[MAX_PLAYERS][18];
new PlayerText:PLottoSchein[MAX_PLAYERS];
new PlayerText:CountdownDraw[MAX_PLAYERS][4];
new PlayerText:LoadingScreen[MAX_PLAYERS][2];
new PlayerText:AchievementDraw[MAX_PLAYERS][6];
new PlayerText:DiceDraw[MAX_PLAYERS][12];
new PlayerText:PaybackKarte[MAX_PLAYERS];
new PlayerText:DashcamTD[MAX_PLAYERS][7];

//Textdraws - RosaLife Reloaded
new Text:Statusleiste[4];
new Text:Time;
new Text:StatusWerbung;
new Text:StatusAFK;
new Text:FlyerDraw[11];
new Text:LottoSchein[7];
new Text:LoginScreen[6];
new Text:DoubleEXPTD[2];
new Text:NoDMZoneTextdraw;
new Text:AlsAdminImDienst;
new Text:PaybackCardTD[12];

new AC_Check[MAX_PLAYERS];